workflows:
  ios-app-sidestore:
    name: Unsigned iOS SideStore Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    working_directory: FILES
    environment:
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Build and Package SwiftUI App
        script: |
          mkdir -p build/Payload/rahhh.app
          SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          FRAMEWORKS_PATH="$SDK_PATH/System/Library/Frameworks"
          
          swiftc -sdk "$SDK_PATH" \
                 -target arm64-apple-ios15.0 \
                 -F "$FRAMEWORKS_PATH" \
                 -parse-as-library \
                 -O -o build/Payload/rahhh.app/rahhh \
                 Sources/rahhh.swift
                 
          cp Info.plist build/Payload/rahhh.app/Info.plist
          cd build
          zip -qy1r rahhh_SideStore.ipa Payload
          rm -rf Payload
    artifacts:
      - FILES/build/*.ipa