      - name: Trigger GitHub Action for nightly release
        script: |
          set -euo pipefail

          TAG_NAME="nightly-$(date +%Y%m%d%H%M%S)"

          curl -sSL -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"event_type\":\"codemagic-ipa-upload\",\"client_payload\":{\"tag_name\":\"$TAG_NAME\",\"asset_names\":[\"rahhh_SideStore.ipa\",\"rahhh_SideStore.ipa.sha256\"]}}" \
            https://api.github.com/repos/Neguy-spec/yes/dispatches
